"""initial

Revision ID: 76fc6f314ffa
Revises: 
Create Date: 2022-06-12 15:37:36.418554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fc6f314ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('name', sa.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.CHAR(length=2), nullable=False),
    sa.ForeignKeyConstraint(['locale'], ['languages.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
